### PR TITLE
Add minimal gas price endpoint

### PR DESCRIPTION
**Pull request by Tasyp**
Exposes [this](https://github.com/MinterTeam/minter-go-node/blob/14439248926def5f6f1d334dc9a84f7d0d2e5a0a/api/min_gas_price.go#L3) API endpoint

### CODE REVIEW

**Comment by shrpne** [comment]
Thank you for PR!
Can you handle Gate's endpoint too? 
https://github.com/MinterTeam/explorer-gate/blob/master/api/main.go#L51

**Comment by Tasyp** [comment]
I've changed the code to support the gate type nodes.

**Comment by shrpne** [comment]
Great!
I will need to add some tests before releasing it.

**Comment by shrpne** [comment]
Released
https://github.com/MinterTeam/minter-js-sdk/releases/tag/v0.21.0

**Pull request merged**
