### PR TITLE
change testnet node url in readme.md examples

### PR DESCRIPTION
**Pull request by kanitelk**
Change testnet node url in readme.md examples and beautify file.

### CODE REVIEW

**Comment by shrpne** [comment]
Thank you for PR, but http://minter-nodes-1.testnet.minter.network:8841 URL doesn't exist

**Comment by kanitelk** [comment]
But... I just checked.
image
image

**Comment by shrpne** [comment]
Looks like browser's HSTS policy redirects to https.
Please change URL to https and remove the port, such URL should work properly

**Comment by kanitelk** [comment]
Thanks.

**Comment by shrpne** [comment]
Well, actually I thought you will update the PR to make it suitable for merge :)

**Comment by kanitelk** [comment]
Ok

**Comment by kanitelk** [comment]
Changed links. Also, VS Code corrected some blank lines on saving.

**Comment by shrpne** [comment]
Merged. Thank you for PR.

**Pull request merged**
